-- =============================================================================
-- Business schema upgrade: 0.2.11 -> 0.2.12 (PostgreSQL)
-- =============================================================================
--
-- Living upgrade path while 0.2.12 is unreleased. Keep this file in sync with
-- develop (procedures.d, schema.xml, post.sql, Static seeds) so a database
-- installed at 0.2.11 can reach the same end state as a fresh 0.2.12 build.
--
-- Fresh installs: make pgsqldb (pre + schema + procedures + post + Static).
-- Do not use this script for a greenfield install.
--
-- PRECONDITIONS
--   * Schema "business" exists
--   * Active SchemaVersion is Business 0.2.11 (stop IS NULL)
--   * Role can ALTER tables, DROP/CREATE views and functions
--   * Backup recommended for production
--
-- HOW TO RUN
--   psql -h <host> -U <user> -d <db> -v ON_ERROR_STOP=1 \
--     -f PostgreSQL/0.2.11-0.2.12.sql
--
-- ---------------------------------------------------------------------------
-- Applied by this script (existing 0.2.11 database)
-- ---------------------------------------------------------------------------
--
--  1) Content, format, site/list placement, campaign tables
--  2) Partial unique indexes (open edition, one live placement, one open run)
--  3) GetParagraph, PluralWord, content and campaign writers
--  4) I18NParagraph and content/campaign read views
--  5) Session.culture, SetSessionCulture, ContentCultures
--  6) Static thank-you content id 10 (en-US, fr-FR, pl-PL, es-MX)
--
-- N) Schema version
--    * SetSchemaVersion('Business', '0', '2', '12') - last substantive step
--
-- =============================================================================


CREATE TABLE IF NOT EXISTS Format (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name integer NOT NULL,
 created timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS FormatAttribute (
 format integer NOT NULL REFERENCES Format (id) DEFERRABLE,
 name integer NOT NULL,
 value integer,
 target integer,
 stop timestamp,
 created timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS formatattribute_format ON FormatAttribute (format);

CREATE TABLE IF NOT EXISTS Content (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name integer NOT NULL,
 created timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ContentEdition (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 content integer NOT NULL REFERENCES Content (id) DEFERRABLE,
 stop timestamp,
 created timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS contentedition_content ON ContentEdition (content);

CREATE TABLE IF NOT EXISTS ContentElement (
 edition integer NOT NULL REFERENCES ContentEdition (id) DEFERRABLE,
 sequence integer NOT NULL,
 word integer,
 sentence integer,
 paragraph integer,
 format integer REFERENCES Format (id) DEFERRABLE,
 argument integer,
 created timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS contentelement_edition_sequence ON ContentElement (edition, sequence);

CREATE TABLE IF NOT EXISTS ContentSite (
 content integer NOT NULL REFERENCES Content (id) DEFERRABLE,
 site integer NOT NULL REFERENCES Site (id) DEFERRABLE,
 sequence integer NOT NULL,
 stop timestamp,
 created timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS contentsite_site ON ContentSite (site);

CREATE TABLE IF NOT EXISTS ContentList (
 content integer NOT NULL REFERENCES Content (id) DEFERRABLE,
 listName integer NOT NULL,
 sequence integer NOT NULL,
 stop timestamp,
 created timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS contentlist_listname ON ContentList (listName);

CREATE TABLE IF NOT EXISTS Campaign (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name integer NOT NULL,
 listName integer NOT NULL,
 listSet integer,
 channel integer,
 period integer REFERENCES PeriodName (period) DEFERRABLE,
 created timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS CampaignRun (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 campaign integer NOT NULL REFERENCES Campaign (id) DEFERRABLE,
 started timestamp NOT NULL DEFAULT NOW(),
 stop timestamp,
 created timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS campaignrun_campaign ON CampaignRun (campaign);

CREATE TABLE IF NOT EXISTS CampaignContent (
 campaign integer NOT NULL REFERENCES Campaign (id) DEFERRABLE,
 content integer NOT NULL REFERENCES Content (id) DEFERRABLE,
 sequence integer NOT NULL,
 stop timestamp,
 created timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS campaigncontent_campaign_sequence ON CampaignContent (campaign, sequence);

CREATE TABLE IF NOT EXISTS CampaignAttachment (
 campaign integer NOT NULL REFERENCES Campaign (id) DEFERRABLE,
 path bigint NOT NULL REFERENCES Path (id) DEFERRABLE,
 sequence integer NOT NULL,
 type integer,
 target integer,
 stop timestamp,
 created timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS campaignattachment_campaign_sequence ON CampaignAttachment (campaign, sequence);

CREATE TABLE IF NOT EXISTS CampaignEvent (
 campaign integer NOT NULL REFERENCES Campaign (id) DEFERRABLE,
 individual bigint NOT NULL,
 kind integer NOT NULL,
 path bigint REFERENCES Path (id) DEFERRABLE,
 run integer REFERENCES CampaignRun (id) DEFERRABLE,
 created timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS campaignevent_campaign_individual ON CampaignEvent (campaign, individual);

ALTER TABLE ContentElement ADD COLUMN IF NOT EXISTS argument integer;

CREATE UNIQUE INDEX IF NOT EXISTS contentedition_content_open
 ON ContentEdition (content) WHERE stop IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS contentelement_edition_sequence_key
 ON ContentElement (edition, sequence);
CREATE UNIQUE INDEX IF NOT EXISTS contentsite_site_content_open
 ON ContentSite (site, content) WHERE stop IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS contentlist_listname_content_open
 ON ContentList (listName, content) WHERE stop IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS campaignrun_campaign_open
 ON CampaignRun (campaign) WHERE stop IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS campaigncontent_campaign_content_open
 ON CampaignContent (campaign, content) WHERE stop IS NULL;


CREATE OR REPLACE FUNCTION GetParagraph (
 paragraph_value text,
 culture_name varchar
) RETURNS integer AS $$
DECLARE
 paragraph_id integer;
 lock_key bigint;
BEGIN
 IF paragraph_value IS NOT NULL THEN
  SELECT id INTO paragraph_id
  FROM Paragraph
  JOIN Culture ON UPPER(Culture.name) = UPPER(culture_name)
  WHERE UPPER(Paragraph.value) = UPPER(paragraph_value)
   AND Paragraph.culture = Culture.code
  LIMIT 1;
  IF paragraph_id IS NULL THEN
   lock_key := hashtext(paragraph_value);
   PERFORM pg_advisory_lock(lock_key);
   BEGIN
    SELECT id INTO paragraph_id
    FROM Paragraph
    JOIN Culture ON UPPER(Culture.name) = UPPER(culture_name)
    WHERE UPPER(Paragraph.value) = UPPER(paragraph_value)
     AND Paragraph.culture = Culture.code
    LIMIT 1;
    IF paragraph_id IS NULL THEN
     INSERT INTO Paragraph (value, culture) (
      SELECT paragraph_value, Culture.code
      FROM Culture
      LEFT JOIN Paragraph AS exists ON UPPER(exists.value) = UPPER(paragraph_value)
       AND exists.culture = Culture.code
      WHERE UPPER(Culture.name) = UPPER(culture_name)
       AND exists.id IS NULL
      LIMIT 1
     );
     SELECT id INTO paragraph_id
     FROM Paragraph
     JOIN Culture ON UPPER(Culture.name) = UPPER(culture_name)
     WHERE UPPER(Paragraph.value) = UPPER(paragraph_value)
      AND Paragraph.culture = Culture.code
     LIMIT 1;
    END IF;
    PERFORM pg_advisory_unlock(lock_key);
   EXCEPTION
    WHEN OTHERS THEN
     PERFORM pg_advisory_unlock(lock_key);
     RAISE;
   END;
  END IF;
 END IF;
 RETURN paragraph_id;
END;
$$ LANGUAGE plpgsql;

-- WordPlural.plural: 0 zero, 2 two, 3 few, 4 many. Singular is the Word itself.
-- 0 -> zero, 1 -> singular, 2 -> two, 3 and 4 -> few, otherwise many.
-- Forms follow ClientCulture() when that culture has the word, else 1033.
CREATE OR REPLACE FUNCTION PluralWord (
 inWord integer,
 inCount integer
) RETURNS varchar AS $$
DECLARE
 form_culture smallint;
 form_value varchar;
BEGIN
 IF inWord IS NULL OR inCount IS NULL THEN
  RETURN NULL;
 END IF;
 form_culture := (
  SELECT w.culture
  FROM Word w
  WHERE w.id = inWord
   AND w.culture = ClientCulture()
  LIMIT 1
 );
 IF form_culture IS NULL THEN
  form_culture := 1033;
 END IF;
 SELECT CASE
  WHEN inCount = 0 THEN zero
  WHEN inCount = 1 THEN singular
  WHEN inCount = 2 THEN two
  WHEN inCount IN (3, 4) THEN few
  ELSE many
 END INTO form_value
 FROM WordPlurals
 WHERE word = inWord
  AND culture = form_culture
 LIMIT 1;
 RETURN form_value;
END;
$$ LANGUAGE plpgsql;

-- Default to en-US
CREATE OR REPLACE FUNCTION GetParagraph (
 paragraph_value text
) RETURNS integer AS $$
DECLARE
BEGIN
 RETURN (
  SELECT GetParagraph(paragraph_value, 'en-US') AS id
 );
END;
$$ LANGUAGE plpgsql;



CREATE OR REPLACE FUNCTION PluralWord (
 inWord integer,
 inCount integer
) RETURNS varchar AS $$
DECLARE
 form_culture smallint;
 form_value varchar;
BEGIN
 IF inWord IS NULL OR inCount IS NULL THEN
  RETURN NULL;
 END IF;
 form_culture := (
  SELECT w.culture
  FROM Word w
  WHERE w.id = inWord
   AND w.culture = ClientCulture()
  LIMIT 1
 );
 IF form_culture IS NULL THEN
  form_culture := 1033;
 END IF;
 SELECT CASE
  WHEN inCount = 0 THEN zero
  WHEN inCount = 1 THEN singular
  WHEN inCount = 2 THEN two
  WHEN inCount IN (3, 4) THEN few
  ELSE many
 END INTO form_value
 FROM WordPlurals
 WHERE word = inWord
  AND culture = form_culture
 LIMIT 1;
 RETURN form_value;
END;
$$ LANGUAGE plpgsql;


-- Content — format groups, editions, site and list placement (diagram: content)

CREATE OR REPLACE FUNCTION SetFormat (
 inName varchar
) RETURNS integer AS $$
DECLARE
 name_id integer;
 format_id integer;
BEGIN
 IF inName IS NOT NULL THEN
  name_id := (SELECT GetSentence(inName));
  PERFORM pg_advisory_lock(name_id);
  BEGIN
   SELECT id INTO format_id
   FROM Format
   WHERE name = name_id
   LIMIT 1;
   IF format_id IS NULL THEN
    INSERT INTO Format (name) (
     SELECT name_id
     FROM Dual
     LEFT JOIN Format AS exists ON exists.name = name_id
     WHERE exists.id IS NULL
     LIMIT 1
    );
    SELECT id INTO format_id
    FROM Format
    WHERE name = name_id
    LIMIT 1;
   END IF;
   PERFORM pg_advisory_unlock(name_id);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(name_id);
    RAISE;
  END;
 END IF;
 RETURN format_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetFormatAttribute (
 inFormat integer,
 inName varchar,
 inValue varchar,
 inTarget varchar
) RETURNS integer AS $$
DECLARE
 name_id integer;
 value_id integer;
 target_id integer;
BEGIN
 IF inFormat IS NOT NULL AND inName IS NOT NULL THEN
  name_id := (SELECT GetWord(inName));
  value_id := (SELECT GetWord(inValue));
  target_id := (SELECT GetWord(inTarget));
  PERFORM pg_advisory_lock(inFormat);
  BEGIN
   INSERT INTO FormatAttribute (format, name, value, target) (
    SELECT inFormat, name_id, value_id, target_id
    FROM Dual
    LEFT JOIN FormatAttribute AS exists ON exists.format = inFormat
     AND exists.name = name_id
     AND ((exists.value = value_id) OR (exists.value IS NULL AND value_id IS NULL))
     AND ((exists.target = target_id) OR (exists.target IS NULL AND target_id IS NULL))
     AND exists.stop IS NULL
    WHERE exists.format IS NULL
    LIMIT 1
   );
   PERFORM pg_advisory_unlock(inFormat);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(inFormat);
    RAISE;
  END;
 END IF;
 RETURN inFormat;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION StopFormatAttribute (
 inFormat integer,
 inName varchar,
 inValue varchar,
 inTarget varchar
) RETURNS integer AS $$
DECLARE
 name_id integer;
 value_id integer;
 target_id integer;
BEGIN
 IF inFormat IS NOT NULL AND inName IS NOT NULL THEN
  name_id := (SELECT GetWord(inName));
  value_id := (SELECT GetWord(inValue));
  target_id := (SELECT GetWord(inTarget));
  PERFORM pg_advisory_lock(inFormat);
  BEGIN
   UPDATE FormatAttribute
   SET stop = NOW()
   WHERE format = inFormat
    AND name = name_id
    AND ((value = value_id) OR (value IS NULL AND value_id IS NULL))
    AND ((target = target_id) OR (target IS NULL AND target_id IS NULL))
    AND stop IS NULL;
   PERFORM pg_advisory_unlock(inFormat);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(inFormat);
    RAISE;
  END;
 END IF;
 RETURN inFormat;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetContent (
 inName varchar
) RETURNS integer AS $$
DECLARE
 name_id integer;
 content_id integer;
BEGIN
 IF inName IS NOT NULL THEN
  name_id := (SELECT GetSentence(inName));
  PERFORM pg_advisory_lock(name_id);
  BEGIN
   SELECT id INTO content_id
   FROM Content
   WHERE name = name_id
   LIMIT 1;
   IF content_id IS NULL THEN
    INSERT INTO Content (name) (
     SELECT name_id
     FROM Dual
     LEFT JOIN Content AS exists ON exists.name = name_id
     WHERE exists.id IS NULL
     LIMIT 1
    );
    SELECT id INTO content_id
    FROM Content
    WHERE name = name_id
    LIMIT 1;
   END IF;
   PERFORM pg_advisory_unlock(name_id);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(name_id);
    RAISE;
  END;
 END IF;
 RETURN content_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION StopContent (
 inContent integer
) RETURNS integer AS $$
BEGIN
 IF inContent IS NOT NULL THEN
  PERFORM pg_advisory_lock(inContent);
  BEGIN
   UPDATE ContentEdition
   SET stop = NOW()
   WHERE content = inContent
    AND stop IS NULL;
   PERFORM pg_advisory_unlock(inContent);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(inContent);
    RAISE;
  END;
 END IF;
 RETURN inContent;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetContentElement (
 inContent integer,
 inSequence integer,
 inFormat integer,
 inWord integer,
 inSentence integer,
 inParagraph integer,
 inArgument varchar
) RETURNS integer AS $$
DECLARE
 edition_id integer;
 atom_count integer;
 argument_id integer;
BEGIN
 atom_count := (inWord IS NOT NULL)::integer
  + (inSentence IS NOT NULL)::integer
  + (inParagraph IS NOT NULL)::integer;
 IF inContent IS NOT NULL
  AND inSequence IS NOT NULL
  AND atom_count = 1 THEN
  IF inWord IS NOT NULL THEN
   argument_id := (SELECT GetWord(inArgument));
  END IF;
  PERFORM pg_advisory_lock(inContent);
  BEGIN
   SELECT id INTO edition_id
   FROM ContentEdition
   WHERE content = inContent
    AND stop IS NULL
   LIMIT 1;
   IF edition_id IS NULL THEN
    INSERT INTO ContentEdition (content) (
     SELECT inContent
     FROM Dual
     LEFT JOIN ContentEdition AS exists ON exists.content = inContent
      AND exists.stop IS NULL
     WHERE exists.id IS NULL
     LIMIT 1
    );
    SELECT id INTO edition_id
    FROM ContentEdition
    WHERE content = inContent
     AND stop IS NULL
    LIMIT 1;
   END IF;
   INSERT INTO ContentElement (edition, sequence, word, sentence, paragraph, format, argument) (
    SELECT edition_id, inSequence, inWord, inSentence, inParagraph, inFormat, argument_id
    FROM Dual
    LEFT JOIN ContentElement AS exists ON exists.edition = edition_id
     AND exists.sequence = inSequence
    WHERE exists.edition IS NULL
    LIMIT 1
   );
   PERFORM pg_advisory_unlock(inContent);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(inContent);
    RAISE;
  END;
 END IF;
 RETURN inContent;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetContentElement (
 inContent integer,
 inSequence integer,
 inFormat integer,
 inWord integer,
 inSentence integer,
 inParagraph integer
) RETURNS integer AS $$
BEGIN
 RETURN (SELECT SetContentElement(inContent, inSequence, inFormat, inWord, inSentence, inParagraph, NULL));
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetContentSite (
 inSite integer,
 inContent integer,
 inSequence integer
) RETURNS integer AS $$
DECLARE
 place integer;
BEGIN
 IF inSite IS NOT NULL AND inContent IS NOT NULL THEN
  place := inSequence;
  IF place IS NULL THEN
   place := (
    SELECT COALESCE(MAX(sequence), 0) + 1
    FROM ContentSite
    WHERE site = inSite
     AND stop IS NULL
   );
  END IF;
  PERFORM pg_advisory_lock(inSite);
  BEGIN
   INSERT INTO ContentSite (content, site, sequence) (
    SELECT inContent, inSite, place
    FROM Dual
    LEFT JOIN ContentSite AS exists ON exists.site = inSite
     AND exists.content = inContent
     AND exists.stop IS NULL
    WHERE exists.content IS NULL
    LIMIT 1
   );
   PERFORM pg_advisory_unlock(inSite);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(inSite);
    RAISE;
  END;
 END IF;
 RETURN inContent;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetContentSite (
 inSite integer,
 inContent integer
) RETURNS integer AS $$
BEGIN
 RETURN (SELECT SetContentSite(inSite, inContent, NULL));
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION StopContentSite (
 inSite integer,
 inContent integer
) RETURNS integer AS $$
BEGIN
 IF inSite IS NOT NULL AND inContent IS NOT NULL THEN
  PERFORM pg_advisory_lock(inSite);
  BEGIN
   UPDATE ContentSite
   SET stop = NOW()
   WHERE site = inSite
    AND content = inContent
    AND stop IS NULL;
   PERFORM pg_advisory_unlock(inSite);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(inSite);
    RAISE;
  END;
 END IF;
 RETURN inContent;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetContentList (
 inListName varchar,
 inContent integer,
 inSequence integer
) RETURNS integer AS $$
DECLARE
 list_id integer;
 place integer;
BEGIN
 IF inListName IS NOT NULL AND inContent IS NOT NULL THEN
  list_id := (SELECT GetWord(inListName));
  place := inSequence;
  IF place IS NULL THEN
   place := (
    SELECT COALESCE(MAX(sequence), 0) + 1
    FROM ContentList
    WHERE listName = list_id
     AND stop IS NULL
   );
  END IF;
  PERFORM pg_advisory_lock(list_id);
  BEGIN
   INSERT INTO ContentList (content, listName, sequence) (
    SELECT inContent, list_id, place
    FROM Dual
    LEFT JOIN ContentList AS exists ON exists.listName = list_id
     AND exists.content = inContent
     AND exists.stop IS NULL
    WHERE exists.content IS NULL
    LIMIT 1
   );
   PERFORM pg_advisory_unlock(list_id);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(list_id);
    RAISE;
  END;
 END IF;
 RETURN inContent;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetContentList (
 inListName varchar,
 inContent integer
) RETURNS integer AS $$
BEGIN
 RETURN (SELECT SetContentList(inListName, inContent, NULL));
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION StopContentList (
 inListName varchar,
 inContent integer
) RETURNS integer AS $$
DECLARE
 list_id integer;
BEGIN
 IF inListName IS NOT NULL AND inContent IS NOT NULL THEN
  list_id := (SELECT GetWord(inListName));
  PERFORM pg_advisory_lock(list_id);
  BEGIN
   UPDATE ContentList
   SET stop = NOW()
   WHERE listName = list_id
    AND content = inContent
    AND stop IS NULL;
   PERFORM pg_advisory_unlock(list_id);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(list_id);
    RAISE;
  END;
 END IF;
 RETURN inContent;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetCampaign (
 inName varchar,
 inListName varchar,
 inListSet varchar,
 inChannel varchar,
 inPeriod integer
) RETURNS integer AS $$
DECLARE
 name_id integer;
 list_id integer;
 set_id integer;
 channel_id integer;
 campaign_id integer;
BEGIN
 IF inName IS NOT NULL AND inListName IS NOT NULL THEN
  name_id := (SELECT GetSentence(inName));
  list_id := (SELECT GetWord(inListName));
  set_id := (SELECT GetWord(inListSet));
  channel_id := (SELECT GetWord(inChannel));
  PERFORM pg_advisory_lock(name_id);
  BEGIN
   SELECT id INTO campaign_id
   FROM Campaign
   WHERE name = name_id
   LIMIT 1;
   IF campaign_id IS NULL THEN
    INSERT INTO Campaign (name, listName, listSet, channel, period) (
     SELECT name_id, list_id, set_id, channel_id, inPeriod
     FROM Dual
     LEFT JOIN Campaign AS exists ON exists.name = name_id
     WHERE exists.id IS NULL
     LIMIT 1
    );
    SELECT id INTO campaign_id
    FROM Campaign
    WHERE name = name_id
    LIMIT 1;
   END IF;
   PERFORM pg_advisory_unlock(name_id);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(name_id);
    RAISE;
  END;
 END IF;
 RETURN campaign_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetCampaign (
 inName varchar,
 inListName varchar
) RETURNS integer AS $$
BEGIN
 RETURN (SELECT SetCampaign(inName, inListName, NULL, NULL, NULL));
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION StartCampaign (
 inCampaign integer
) RETURNS integer AS $$
BEGIN
 IF inCampaign IS NOT NULL THEN
  PERFORM pg_advisory_lock(inCampaign);
  BEGIN
   INSERT INTO CampaignRun (campaign) (
    SELECT inCampaign
    FROM Dual
    LEFT JOIN CampaignRun AS exists ON exists.campaign = inCampaign
     AND exists.stop IS NULL
    WHERE exists.id IS NULL
    LIMIT 1
   );
   PERFORM pg_advisory_unlock(inCampaign);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(inCampaign);
    RAISE;
  END;
 END IF;
 RETURN inCampaign;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION StopCampaign (
 inCampaign integer
) RETURNS integer AS $$
BEGIN
 IF inCampaign IS NOT NULL THEN
  PERFORM pg_advisory_lock(inCampaign);
  BEGIN
   UPDATE CampaignRun
   SET stop = NOW()
   WHERE campaign = inCampaign
    AND stop IS NULL;
   PERFORM pg_advisory_unlock(inCampaign);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(inCampaign);
    RAISE;
  END;
 END IF;
 RETURN inCampaign;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetCampaignContent (
 inCampaign integer,
 inContent integer,
 inSequence integer
) RETURNS integer AS $$
DECLARE
 place integer;
BEGIN
 IF inCampaign IS NOT NULL AND inContent IS NOT NULL THEN
  place := inSequence;
  IF place IS NULL THEN
   place := (
    SELECT COALESCE(MAX(sequence), 0) + 1
    FROM CampaignContent
    WHERE campaign = inCampaign
     AND stop IS NULL
   );
  END IF;
  PERFORM pg_advisory_lock(inCampaign);
  BEGIN
   INSERT INTO CampaignContent (campaign, content, sequence) (
    SELECT inCampaign, inContent, place
    FROM Dual
    LEFT JOIN CampaignContent AS exists ON exists.campaign = inCampaign
     AND exists.content = inContent
     AND exists.stop IS NULL
    WHERE exists.content IS NULL
    LIMIT 1
   );
   PERFORM pg_advisory_unlock(inCampaign);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(inCampaign);
    RAISE;
  END;
 END IF;
 RETURN inCampaign;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetCampaignContent (
 inCampaign integer,
 inContent integer
) RETURNS integer AS $$
BEGIN
 RETURN (SELECT SetCampaignContent(inCampaign, inContent, NULL));
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION StopCampaignContent (
 inCampaign integer,
 inContent integer
) RETURNS integer AS $$
BEGIN
 IF inCampaign IS NOT NULL AND inContent IS NOT NULL THEN
  PERFORM pg_advisory_lock(inCampaign);
  BEGIN
   UPDATE CampaignContent
   SET stop = NOW()
   WHERE campaign = inCampaign
    AND content = inContent
    AND stop IS NULL;
   PERFORM pg_advisory_unlock(inCampaign);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(inCampaign);
    RAISE;
  END;
 END IF;
 RETURN inCampaign;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetCampaignAttachment (
 inCampaign integer,
 inPath bigint,
 inSequence integer,
 inType varchar,
 inTarget varchar
) RETURNS integer AS $$
DECLARE
 place integer;
 type_id integer;
 target_id integer;
BEGIN
 IF inCampaign IS NOT NULL AND inPath IS NOT NULL THEN
  type_id := (SELECT GetWord(inType));
  target_id := (SELECT GetWord(inTarget));
  place := inSequence;
  IF place IS NULL THEN
   place := (
    SELECT COALESCE(MAX(sequence), 0) + 1
    FROM CampaignAttachment
    WHERE campaign = inCampaign
     AND stop IS NULL
   );
  END IF;
  PERFORM pg_advisory_lock(inCampaign);
  BEGIN
   INSERT INTO CampaignAttachment (campaign, path, sequence, type, target) (
    SELECT inCampaign, inPath, place, type_id, target_id
    FROM Dual
    LEFT JOIN CampaignAttachment AS exists ON exists.campaign = inCampaign
     AND exists.path = inPath
     AND ((exists.type = type_id) OR (exists.type IS NULL AND type_id IS NULL))
     AND ((exists.target = target_id) OR (exists.target IS NULL AND target_id IS NULL))
     AND exists.stop IS NULL
    WHERE exists.path IS NULL
    LIMIT 1
   );
   PERFORM pg_advisory_unlock(inCampaign);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(inCampaign);
    RAISE;
  END;
 END IF;
 RETURN inCampaign;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetCampaignAttachment (
 inCampaign integer,
 inPath bigint,
 inType varchar,
 inTarget varchar
) RETURNS integer AS $$
BEGIN
 RETURN (SELECT SetCampaignAttachment(inCampaign, inPath, NULL, inType, inTarget));
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION StopCampaignAttachment (
 inCampaign integer,
 inPath bigint,
 inType varchar,
 inTarget varchar
) RETURNS integer AS $$
DECLARE
 type_id integer;
 target_id integer;
BEGIN
 IF inCampaign IS NOT NULL AND inPath IS NOT NULL THEN
  type_id := (SELECT GetWord(inType));
  target_id := (SELECT GetWord(inTarget));
  PERFORM pg_advisory_lock(inCampaign);
  BEGIN
   UPDATE CampaignAttachment
   SET stop = NOW()
   WHERE campaign = inCampaign
    AND path = inPath
    AND ((type = type_id) OR (type IS NULL AND type_id IS NULL))
    AND ((target = target_id) OR (target IS NULL AND target_id IS NULL))
    AND stop IS NULL;
   PERFORM pg_advisory_unlock(inCampaign);
  EXCEPTION
   WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(inCampaign);
    RAISE;
  END;
 END IF;
 RETURN inCampaign;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION SetCampaignEvent (
 inCampaign integer,
 inIndividual bigint,
 inKind varchar,
 inPath bigint,
 inRun integer
) RETURNS integer AS $$
DECLARE
 kind_id integer;
BEGIN
 IF inCampaign IS NOT NULL AND inIndividual IS NOT NULL AND inKind IS NOT NULL THEN
  kind_id := (SELECT GetWord(inKind));
  INSERT INTO CampaignEvent (campaign, individual, kind, path, run)
  VALUES (inCampaign, inIndividual, kind_id, inPath, inRun);
 END IF;
 RETURN inCampaign;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE VIEW I18NParagraph AS
SELECT ParagraphDefault.id,
 ParagraphDefault.culture AS defaultCulture,
 ClientCulture() AS clientCulture,
 COALESCE(Paragraph.culture, ParagraphDefault.culture) AS resultCulture,
 COALESCE(Paragraph.value, ParagraphDefault.value) AS value
FROM Paragraph AS ParagraphDefault
LEFT JOIN Paragraph ON Paragraph.id = ParagraphDefault.id
 AND Paragraph.culture = ClientCulture()
WHERE ParagraphDefault.culture = 1033;

CREATE OR REPLACE VIEW FormatAttributes AS
SELECT FormatAttribute.format,
 Name.value AS name,
 Value.value AS value,
 Target.value AS target,
 FormatAttribute.created
FROM FormatAttribute
LEFT JOIN I18NWord AS Name ON Name.id = FormatAttribute.name
LEFT JOIN I18NWord AS Value ON Value.id = FormatAttribute.value
LEFT JOIN I18NWord AS Target ON Target.id = FormatAttribute.target
WHERE FormatAttribute.stop IS NULL;

CREATE OR REPLACE VIEW ContentElements AS
SELECT ContentEdition.content,
 ContentEdition.id AS edition,
 ContentElement.sequence,
 CASE
  WHEN ContentElement.word IS NOT NULL THEN 'word'
  WHEN ContentElement.sentence IS NOT NULL THEN 'sentence'
  ELSE 'paragraph'
 END AS kind,
 COALESCE(ContentElement.word, ContentElement.sentence, ContentElement.paragraph) AS element,
 COALESCE(I18NWord.value, I18NSentence.value, I18NParagraph.value) AS value,
 ContentElement.format,
 ContentEdition.created,
 Argument.value AS argument
FROM ContentEdition
JOIN ContentElement ON ContentElement.edition = ContentEdition.id
LEFT JOIN I18NWord ON I18NWord.id = ContentElement.word
LEFT JOIN I18NSentence ON I18NSentence.id = ContentElement.sentence
LEFT JOIN I18NParagraph ON I18NParagraph.id = ContentElement.paragraph
LEFT JOIN I18NWord AS Argument ON Argument.id = ContentElement.argument
WHERE ContentEdition.stop IS NULL;

CREATE OR REPLACE VIEW ContentElementPlurals AS
SELECT ContentEdition.content,
 ContentEdition.id AS edition,
 ContentElement.sequence,
 Argument.value AS argument,
 ContentElement.word,
 Forms.singular,
 Forms.zero,
 Forms.two,
 Forms.few,
 Forms.many
FROM ContentEdition
JOIN ContentElement ON ContentElement.edition = ContentEdition.id
 AND ContentElement.word IS NOT NULL
 AND ContentElement.argument IS NOT NULL
LEFT JOIN I18NWord AS Argument ON Argument.id = ContentElement.argument
LEFT JOIN WordPlurals AS Forms ON Forms.word = ContentElement.word
 AND Forms.culture = COALESCE(
  (SELECT w.culture FROM Word w WHERE w.id = ContentElement.word AND w.culture = ClientCulture() LIMIT 1),
  1033)
WHERE ContentEdition.stop IS NULL;

CREATE OR REPLACE VIEW ContentHistory AS
SELECT ContentEdition.content,
 ContentEdition.id AS edition,
 ContentElement.sequence,
 CASE
  WHEN ContentElement.word IS NOT NULL THEN 'word'
  WHEN ContentElement.sentence IS NOT NULL THEN 'sentence'
  ELSE 'paragraph'
 END AS kind,
 COALESCE(ContentElement.word, ContentElement.sentence, ContentElement.paragraph) AS element,
 COALESCE(I18NWord.value, I18NSentence.value, I18NParagraph.value) AS value,
 ContentElement.format,
 ContentEdition.stop,
 ContentEdition.created
FROM ContentEdition
JOIN ContentElement ON ContentElement.edition = ContentEdition.id
LEFT JOIN I18NWord ON I18NWord.id = ContentElement.word
LEFT JOIN I18NSentence ON I18NSentence.id = ContentElement.sentence
LEFT JOIN I18NParagraph ON I18NParagraph.id = ContentElement.paragraph;

CREATE OR REPLACE VIEW ContentSites AS
SELECT site, content, sequence, created
FROM ContentSite
WHERE stop IS NULL;

CREATE OR REPLACE VIEW ContentLists AS
SELECT ContentList.listName,
 Name.value AS listNameValue,
 ContentList.content,
 ContentList.sequence,
 ContentList.created
FROM ContentList
LEFT JOIN I18NWord AS Name ON Name.id = ContentList.listName
WHERE ContentList.stop IS NULL;

CREATE OR REPLACE VIEW CampaignContents AS
SELECT campaign, content, sequence, created
FROM CampaignContent
WHERE stop IS NULL;

CREATE OR REPLACE VIEW CampaignAttachments AS
SELECT CampaignAttachment.campaign,
 CampaignAttachment.path,
 CampaignAttachment.sequence,
 Type.value AS type,
 Target.value AS target,
 CampaignAttachment.created
FROM CampaignAttachment
LEFT JOIN I18NWord AS Type ON Type.id = CampaignAttachment.type
LEFT JOIN I18NWord AS Target ON Target.id = CampaignAttachment.target
WHERE CampaignAttachment.stop IS NULL;

CREATE OR REPLACE VIEW CampaignRuns AS
SELECT id AS run, campaign, started, stop, created
FROM CampaignRun;

CREATE OR REPLACE VIEW CampaignEvents AS
SELECT CampaignEvent.campaign,
 CampaignEvent.individual,
 Kind.value AS kind,
 CampaignEvent.path,
 CampaignEvent.run,
 CampaignEvent.created
FROM CampaignEvent
LEFT JOIN I18NWord AS Kind ON Kind.id = CampaignEvent.kind;

CREATE OR REPLACE VIEW CampaignRecipients AS
SELECT Campaign.id AS campaign,
 ListIndividual.individual,
 EmailAddress.value AS email,
 IndividualAddress.address
FROM Campaign
JOIN ListIndividualName ON ListIndividualName.name = Campaign.listName
 AND (Campaign.listSet IS NULL OR ListIndividualName.listSet = Campaign.listSet)
JOIN ListIndividual ON ListIndividual.id = ListIndividualName.listIndividual
 AND ListIndividual.unlist IS NULL
LEFT JOIN IndividualEmail ON IndividualEmail.individual = ListIndividual.individual
 AND IndividualEmail.stop IS NULL
 AND IndividualEmail.type IS NULL
LEFT JOIN EmailAddress ON EmailAddress.email = IndividualEmail.email
LEFT JOIN IndividualAddress ON IndividualAddress.individual = ListIndividual.individual
 AND IndividualAddress.stop IS NULL
 AND IndividualAddress.type IS NULL;


ALTER TABLE Session ADD COLUMN IF NOT EXISTS culture smallint;

-- NULL culture name clears Session.culture (en-US fallback).
CREATE OR REPLACE FUNCTION SetSessionCulture (
 inSession bigint,
 inCulture varchar
) RETURNS bigint AS $$
DECLARE
 culture_code smallint;
BEGIN
 IF inSession IS NULL THEN
  RETURN NULL;
 END IF;
 IF inCulture IS NULL THEN
  UPDATE Session SET culture = NULL WHERE id = inSession;
 ELSE
  SELECT code INTO culture_code
  FROM Culture
  WHERE UPPER(name) = UPPER(inCulture);
  IF culture_code IS NOT NULL THEN
   UPDATE Session SET culture = culture_code WHERE id = inSession;
  END IF;
 END IF;
 RETURN inSession;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE VIEW ContentCultures AS
WITH open_edition AS (
 SELECT id, content
 FROM ContentEdition
 WHERE stop IS NULL
),
elem AS (
 SELECT open_edition.content, ContentElement.word, ContentElement.sentence, ContentElement.paragraph
 FROM open_edition
 JOIN ContentElement ON ContentElement.edition = open_edition.id
),
candidate AS (
 SELECT elem.content, Word.culture
 FROM elem
 JOIN Word ON Word.id = elem.word
 UNION
 SELECT elem.content, WordPlural.culture
 FROM elem
 JOIN WordPlural ON WordPlural.word = elem.word
 UNION
 SELECT elem.content, Sentence.culture
 FROM elem
 JOIN Sentence ON Sentence.id = elem.sentence
 UNION
 SELECT elem.content, Paragraph.culture
 FROM elem
 JOIN Paragraph ON Paragraph.id = elem.paragraph
 UNION
 SELECT content, 1033
 FROM open_edition
)
SELECT candidate.content,
 candidate.culture,
 Culture.name
FROM candidate
JOIN Culture ON Culture.code = candidate.culture
WHERE NOT EXISTS (
 SELECT 1
 FROM elem
 WHERE elem.content = candidate.content
 AND (
  (elem.word IS NOT NULL AND NOT (
    EXISTS (SELECT 1 FROM Word WHERE Word.id = elem.word AND Word.culture = candidate.culture)
    OR EXISTS (SELECT 1 FROM WordPlural WHERE WordPlural.word = elem.word AND WordPlural.culture = candidate.culture)
  ))
  OR (elem.sentence IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM Sentence WHERE Sentence.id = elem.sentence AND Sentence.culture = candidate.culture
  ))
  OR (elem.paragraph IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM Paragraph WHERE Paragraph.id = elem.paragraph AND Paragraph.culture = candidate.culture
  ))
 )
);

CREATE OR REPLACE VIEW IndividualSessions AS
WITH bound (individual, sessionCredential, bound) AS (
 SELECT individual, sessionCredential, created
 FROM IndividualSessionCreated
 UNION
 SELECT Credential.individual, SessionCredential.id, SessionCredential.created
 FROM SessionCredential
 JOIN Credential ON Credential.id = SessionCredential.credential
  AND Credential.revoked IS NULL
  AND Credential.individual IS NOT NULL
)
SELECT
 bound.individual,
 COALESCE(People.fullName, Entities.name) AS individualName,
 Session.id AS session,
 SessionToken.token,
 Type.value AS tokenType,
 SessionToken.siteApplicationRelease,
 Site.id AS site,
 SessionCredential.id AS sessionCredential,
 SessionCredential.credential,
 Credential.username,
 EmailAddress.value AS email,
 bound.bound,
 Session.touched,
 COALESCE(SessionToken.created, Session.created) AS created,
 SiteName.value AS siteName,
 Session.culture
FROM bound
JOIN SessionCredential ON SessionCredential.id = bound.sessionCredential
JOIN Session ON Session.id = SessionCredential.session
JOIN Credential ON Credential.id = SessionCredential.credential
 AND Credential.revoked IS NULL
LEFT JOIN SessionToken ON SessionToken.session = Session.id
LEFT JOIN I18NWord AS Type ON Type.id = SessionToken.type
LEFT JOIN SiteApplicationRelease ON SiteApplicationRelease.id = SessionToken.siteApplicationRelease
LEFT JOIN Site ON Site.id = SiteApplicationRelease.site
LEFT JOIN I18NSentence AS SiteName ON SiteName.id = Site.name
LEFT JOIN People ON People.individual = bound.individual
LEFT JOIN Entities ON Entities.individual = bound.individual
LEFT JOIN EmailAddress ON EmailAddress.email = Credential.email;


INSERT INTO Word (id,culture,value) SELECT 80110,1033,'subscription' WHERE NOT EXISTS (SELECT 1 FROM Word WHERE id=80110 AND culture=1033);
INSERT INTO Word (id,culture,value) SELECT 80110,1036,'abonnement' WHERE NOT EXISTS (SELECT 1 FROM Word WHERE id=80110 AND culture=1036);
INSERT INTO Word (id,culture,value) SELECT 80110,1045,'subskrypcja' WHERE NOT EXISTS (SELECT 1 FROM Word WHERE id=80110 AND culture=1045);
INSERT INTO Word (id,culture,value) SELECT 80110,2058,'suscripción' WHERE NOT EXISTS (SELECT 1 FROM Word WHERE id=80110 AND culture=2058);
INSERT INTO Word (id,culture,value) SELECT 80111,1033,'subscriptions' WHERE NOT EXISTS (SELECT 1 FROM Word WHERE id=80111 AND culture=1033);
INSERT INTO Word (id,culture,value) SELECT 80111,1036,'abonnements' WHERE NOT EXISTS (SELECT 1 FROM Word WHERE id=80111 AND culture=1036);
INSERT INTO Word (id,culture,value) SELECT 80111,1045,'subskrypcje' WHERE NOT EXISTS (SELECT 1 FROM Word WHERE id=80111 AND culture=1045);
INSERT INTO Word (id,culture,value) SELECT 80111,2058,'suscripciones' WHERE NOT EXISTS (SELECT 1 FROM Word WHERE id=80111 AND culture=2058);
INSERT INTO Word (id,culture,value) SELECT 80112,1045,'subskrypcji' WHERE NOT EXISTS (SELECT 1 FROM Word WHERE id=80112 AND culture=1045);
INSERT INTO Sentence (id,culture,value,length) SELECT 80110,1033,'Thank you for your',18 WHERE NOT EXISTS (SELECT 1 FROM Sentence WHERE id=80110 AND culture=1033);
INSERT INTO Sentence (id,culture,value,length) SELECT 80110,1036,'Merci pour votre',16 WHERE NOT EXISTS (SELECT 1 FROM Sentence WHERE id=80110 AND culture=1036);
INSERT INTO Sentence (id,culture,value,length) SELECT 80110,1045,'Dziękuję za Twoją',17 WHERE NOT EXISTS (SELECT 1 FROM Sentence WHERE id=80110 AND culture=1045);
INSERT INTO Sentence (id,culture,value,length) SELECT 80110,2058,'Gracias por tu',14 WHERE NOT EXISTS (SELECT 1 FROM Sentence WHERE id=80110 AND culture=2058);
INSERT INTO Sentence (id,culture,value,length) SELECT 80130,1033,'Thank you',9 WHERE NOT EXISTS (SELECT 1 FROM Sentence WHERE id=80130 AND culture=1033);
INSERT INTO Sentence (id,culture,value,length) SELECT 80130,1036,'Merci',5 WHERE NOT EXISTS (SELECT 1 FROM Sentence WHERE id=80130 AND culture=1036);
INSERT INTO Sentence (id,culture,value,length) SELECT 80130,1045,'Dziękuję',8 WHERE NOT EXISTS (SELECT 1 FROM Sentence WHERE id=80130 AND culture=1045);
INSERT INTO Sentence (id,culture,value,length) SELECT 80130,2058,'Gracias',7 WHERE NOT EXISTS (SELECT 1 FROM Sentence WHERE id=80130 AND culture=2058);
INSERT INTO WordPlural (id, culture, word, plural, form) SELECT 50, 1033, 80110, 0, 80111 WHERE NOT EXISTS (SELECT 1 FROM WordPlural WHERE id=50);
INSERT INTO WordPlural (id, culture, word, plural, form) SELECT 51, 1033, 80110, 3, 80111 WHERE NOT EXISTS (SELECT 1 FROM WordPlural WHERE id=51);
INSERT INTO WordPlural (id, culture, word, plural, form) SELECT 52, 1036, 80110, 0, 80110 WHERE NOT EXISTS (SELECT 1 FROM WordPlural WHERE id=52);
INSERT INTO WordPlural (id, culture, word, plural, form) SELECT 53, 1036, 80110, 3, 80111 WHERE NOT EXISTS (SELECT 1 FROM WordPlural WHERE id=53);
INSERT INTO WordPlural (id, culture, word, plural, form) SELECT 54, 1045, 80110, 0, 80110 WHERE NOT EXISTS (SELECT 1 FROM WordPlural WHERE id=54);
INSERT INTO WordPlural (id, culture, word, plural, form) SELECT 55, 1045, 80110, 3, 80111 WHERE NOT EXISTS (SELECT 1 FROM WordPlural WHERE id=55);
INSERT INTO WordPlural (id, culture, word, plural, form) SELECT 56, 1045, 80110, 4, 80112 WHERE NOT EXISTS (SELECT 1 FROM WordPlural WHERE id=56);
INSERT INTO WordPlural (id, culture, word, plural, form) SELECT 57, 2058, 80110, 0, 80111 WHERE NOT EXISTS (SELECT 1 FROM WordPlural WHERE id=57);
INSERT INTO WordPlural (id, culture, word, plural, form) SELECT 58, 2058, 80110, 3, 80111 WHERE NOT EXISTS (SELECT 1 FROM WordPlural WHERE id=58);
INSERT INTO Content (id, name) SELECT 10, 80130 WHERE NOT EXISTS (SELECT 1 FROM Content WHERE id=10);
INSERT INTO ContentEdition (id, content) SELECT 10, 10 WHERE NOT EXISTS (SELECT 1 FROM ContentEdition WHERE id=10);
INSERT INTO ContentElement (edition, sequence, sentence) SELECT 10, 1, 80110 WHERE NOT EXISTS (SELECT 1 FROM ContentElement WHERE edition=10 AND sequence=1);
INSERT INTO ContentElement (edition, sequence, word, argument) SELECT 10, 2, 80110, 80111 WHERE NOT EXISTS (SELECT 1 FROM ContentElement WHERE edition=10 AND sequence=2);

-- Mark schema upgraded to 0.2.12 when the hop body is ready for the release.
-- Until then, leave this commented so a partial living script is not stamped
-- as 0.2.12 on production by mistake.
-- SELECT SetSchemaVersion('Business', '0', '2', '12');
