-- =============================================================================
-- Business schema upgrade: 0.2.12 -> 0.2.13 (SQLite shop)
-- =============================================================================
--
-- Living upgrade path while 0.2.13 is unreleased. Apply to a shop DB that was
-- built or upgraded to 0.2.12 so it reaches the same end state as a fresh
-- 0.2.13 business.sqlite3 template (DDL + seeds that Static would add).
--
-- Fresh shops: make business.sqlite3 / make rebuild-business-sqlite3.
-- Do not use this script for a greenfield create.
--
-- PRECONDITIONS (enforced by scripts/upgrade-sqlite.sh)
--   * SQLITE_DB points at the live shop file
--   * Active SchemaVersion is Business 0.2.12 (stop IS NULL)
--   * File backup taken (script can .backup before apply)
--
-- HOW TO RUN
--   export SQLITE_DB=$HOME/business-shop/business.sqlite3
--   ./scripts/upgrade-sqlite.sh 0.2.12 0.2.13
--
-- ---------------------------------------------------------------------------
-- Applied by this script (existing 0.2.12 shop database)
-- ---------------------------------------------------------------------------
--
--  (none yet)
--
-- SQLite does not enforce varchar(n). Width-only ALTERs are no-ops here.
--
-- Version stamp is performed by scripts/upgrade-sqlite.sh via SetSchemaVersion
-- after this file runs successfully (Business 0.2.13) when STAMP_VERSION=1.
-- Leave STAMP_VERSION unset until that release.
--
-- =============================================================================

PRAGMA foreign_keys = ON;
