-- DEPRECATED: views moved into schema.xml (all dialects).
--
-- Use after regenerating schema:
--   make schema.sqlite && make rebuild-business-sqlite3
--
-- Views:
--   BillDocuments, InvoiceLineDetail, PartyAddresses, PartyPhones, BillReferences
--
-- Living upgrade hops: PostgreSQL/0.2.12-0.2.13.sql and SQLite/0.2.12-0.2.13.sql
--
-- This file is kept only so old docs that reference it do not 404.
SELECT 'Use schema.xml views BillDocuments / InvoiceLineDetail / Party* / BillReferences' AS notice;
