#!/usr/bin/env bash

# Usage: GetURL <secure> <host> <value> <get> [port]
# Wrapper: GetPath http ...  Parity with PG GetURL.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
exec "$HERE/GetPath" http "$@"
