INSERT INTO Sentence (id,culture,value,length) VALUES(1,1033,'IBM Information Management System',33);
INSERT INTO Sentence (id,culture,value,length) VALUES(2,1033,'Unknown',7);
INSERT INTO Sentence (id,culture,value,length) VALUES(3,1033,'Christmas Day',13);
INSERT INTO Sentence (id,culture,value,length) VALUES(4,1033,'Thanksgiving Day',16);
INSERT INTO Sentence (id,culture,value,length) VALUES(5,1033,'Veterans Day',12);
INSERT INTO Sentence (id,culture,value,length) VALUES(6,1033,'Memorial Day',12);
INSERT INTO Sentence (id,culture,value,length) VALUES(7,1033,'New Years Day',13);
INSERT INTO Sentence (id,culture,value,length) VALUES(8,1033,'Martin Luther King, Jr. Day',27);
INSERT INTO Sentence (id,culture,value,length) VALUES(9,1033,'George Washington''s Birthday',29);
INSERT INTO Sentence (id,culture,value,length) VALUES(10,1033,'Independence Day',17);
INSERT INTO Sentence (id,culture,value,length) VALUES(11,1033,'Labor Day',9);
INSERT INTO Sentence (id,culture,value,length) VALUES(12,1033,'Columbus Day',12);
INSERT INTO Sentence (id,culture,value,length) VALUES(13,1033,'Valentine''s Day',16);
INSERT INTO Sentence (id,culture,value,length) VALUES(14,1033,'Breakfast',9);
INSERT INTO Sentence (id,culture,value,length) VALUES(15,1033,'Second breakfast',16);
INSERT INTO Sentence (id,culture,value,length) VALUES(16,1033,'Brunch',6);
INSERT INTO Sentence (id,culture,value,length) VALUES(17,1033,'Elevenses',9);
INSERT INTO Sentence (id,culture,value,length) VALUES(18,1033,'Morning tea',11);
INSERT INTO Sentence (id,culture,value,length) VALUES(19,1033,'Lunch',5);
INSERT INTO Sentence (id,culture,value,length) VALUES(20,1033,'Tea',3);
INSERT INTO Sentence (id,culture,value,length) VALUES(21,1033,'Linner',6);
INSERT INTO Sentence (id,culture,value,length) VALUES(22,1033,'Supper',6);
INSERT INTO Sentence (id,culture,value,length) VALUES(23,1033,'Dinner',6);
INSERT INTO Sentence (id,culture,value,length) VALUES(24,1033,'Holiday Dinner',14);
INSERT INTO Sentence (id,culture,value,length) VALUES(25,1033,'Midnight Snack',14);
INSERT INTO Sentence (id,culture,value,length) VALUES(26,1033,'Black History Month',19);
INSERT INTO Sentence (id,culture,value,length) VALUES(27,1033,'5th of May',10);
INSERT INTO Sentence (id,culture,value,length) VALUES(27,2058,'Cinco de Mayo',13);
INSERT INTO Sentence (id,culture,value,length) VALUES(28,1033,'Day of the Taco',15);
INSERT INTO Sentence (id,culture,value,length) VALUES(28,2058,'Día del Taco',12);
INSERT INTO Sentence (id,culture,value,length) VALUES(29,1033,'National Taco Day',17);

-- Accounting Sentences
INSERT INTO Sentence (id,culture,value,length) VALUES (70,1033,'Asset',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (71,1033,'Liability',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (72,1033,'Income',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (73,1033,'Expenses',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (74,1033,'Equity',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (75,1033,'Bank',4);
INSERT INTO Sentence (id,culture,value,length) VALUES (76,1033,'Cash',4);
INSERT INTO Sentence (id,culture,value,length) VALUES (77,1033,'Loan',4);
INSERT INTO Sentence (id,culture,value,length) VALUES (78,1033,'Equipment',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (79,1033,'Payable',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (81,1033,'Salary',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (82,1033,'Doubtful Accounts',17);
INSERT INTO Sentence (id,culture,value,length) VALUES (83,1033,'Depreciation',12);
INSERT INTO Sentence (id,culture,value,length) VALUES (84,1033,'General',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (90,1033,'Receivable',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (91,1033,'Current Assets',14);
INSERT INTO Sentence (id,culture,value,length) VALUES (92,1033,'Retained Earnings',17);
INSERT INTO Sentence (id,culture,value,length) VALUES (93,1033,'Discounts',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (94,1033,'Service Charges',15);
INSERT INTO Sentence (id,culture,value,length) VALUES (95,1033,'Charity',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (96,1033,'Dining',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (97,1033,'Dues and Subscriptions',22);
INSERT INTO Sentence (id,culture,value,length) VALUES (98,1033,'Insurance',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (99,1033,'Licenses and Permits',20);
INSERT INTO Sentence (id,culture,value,length) VALUES (100,1033,'Supplies',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (101,1033,'Rental',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (102,1033,'Miscellaneous',13);
INSERT INTO Sentence (id,culture,value,length) VALUES (103,1033,'Payroll',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (104,1033,'Postage',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (105,1033,'Media',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (106,1033,'Professional Fees',17);
INSERT INTO Sentence (id,culture,value,length) VALUES (107,1033,'Rent',4);
INSERT INTO Sentence (id,culture,value,length) VALUES (108,1033,'Repairs',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (109,1033,'Taxes',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (110,1033,'Travel and Entertainment',24);
INSERT INTO Sentence (id,culture,value,length) VALUES (111,1033,'Utilities',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (112,1033,'Sales',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (113,1033,'Interest Income',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (114,1033,'Reimbursed Expenses',19);
INSERT INTO Sentence (id,culture,value,length) VALUES (115,1033,'Credit Card',11);
INSERT INTO Sentence (id,culture,value,length) VALUES (116,1033,'Sales Credits',13);
INSERT INTO Sentence (id,culture,value,length) VALUES (117,1033,'Purchases',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (118,1033,'Purchases Debit',15);
INSERT INTO Sentence (id,culture,value,length) VALUES (119,1033,'Receipts',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (120,1033,'Payments',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (121,1033,'Petty Cash',10);
