INSERT INTO Sentence (id,culture,value,length) VALUES (1,1033,'IBM Information Management System',33);
INSERT INTO Sentence (id,culture,value,length) VALUES (2,1033,'Unknown',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (3,1033,'Christmas Day',13);
INSERT INTO Sentence (id,culture,value,length) VALUES (4,1033,'Thanksgiving Day',16);
INSERT INTO Sentence (id,culture,value,length) VALUES (5,1033,'Veterans Day',12);
INSERT INTO Sentence (id,culture,value,length) VALUES (6,1033,'Memorial Day',12);
INSERT INTO Sentence (id,culture,value,length) VALUES (7,1033,'New Years Day',13);
INSERT INTO Sentence (id,culture,value,length) VALUES (8,1033,'Martin Luther King, Jr. Day',27);
INSERT INTO Sentence (id,culture,value,length) VALUES (9,1033,'George Washington''s Birthday',29);
INSERT INTO Sentence (id,culture,value,length) VALUES (10,1033,'Independence Day',17);
INSERT INTO Sentence (id,culture,value,length) VALUES (11,1033,'Labor Day',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (12,1033,'Columbus Day',12);
INSERT INTO Sentence (id,culture,value,length) VALUES (13,1033,'Valentine''s Day',16);
INSERT INTO Sentence (id,culture,value,length) VALUES (14,1033,'Breakfast',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (15,1033,'Second breakfast',16);
INSERT INTO Sentence (id,culture,value,length) VALUES (16,1033,'Brunch',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (17,1033,'Elevenses',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (18,1033,'Morning tea',11);
INSERT INTO Sentence (id,culture,value,length) VALUES (19,1033,'Lunch',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (20,1033,'Tea',3);
INSERT INTO Sentence (id,culture,value,length) VALUES (21,1033,'Linner',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (22,1033,'Supper',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (23,1033,'Dinner',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (24,1033,'Holiday Dinner',14);
INSERT INTO Sentence (id,culture,value,length) VALUES (25,1033,'Midnight Snack',14);
INSERT INTO Sentence (id,culture,value,length) VALUES (26,1033,'Black History Month',19);
INSERT INTO Sentence (id,culture,value,length) VALUES (27,1033,'5th of May',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (27,2058,'Cinco de Mayo',13);
INSERT INTO Sentence (id,culture,value,length) VALUES (28,1033,'Day of the Taco',15);
INSERT INTO Sentence (id,culture,value,length) VALUES (28,2058,'Día del Taco',12);
INSERT INTO Sentence (id,culture,value,length) VALUES (29,1033,'National Taco Day',17);

-- Accounting Sentences
INSERT INTO Sentence (id,culture,value,length) VALUES (70,1033,'Asset',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (70,1036,'le capital',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (70,2058,'la posesión capital',19);
INSERT INTO Sentence (id,culture,value,length) VALUES (71,1033,'Liability',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (71,1036,'les dettes',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (71,2058,'la obligación',13);
INSERT INTO Sentence (id,culture,value,length) VALUES (72,1033,'Income',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (72,1036,'Revenu',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (72,2058,'Ingreso',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (73,1033,'Expenses',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (73,1036,'Dépenses',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (73,2058,'las expensas',12);
INSERT INTO Sentence (id,culture,value,length) VALUES (74,1033,'Equity',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (74,1036,'les fonds',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (74,2058,'Capital',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (75,1033,'Bank',4);
INSERT INTO Sentence (id,culture,value,length) VALUES (75,1036,'Banque',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (75,2058,'Banco',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (76,1033,'Cash',4);
INSERT INTO Sentence (id,culture,value,length) VALUES (76,1036,'encaisser',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (76,2058,'Dinero en efectivo',18);
INSERT INTO Sentence (id,culture,value,length) VALUES (77,1033,'Loan',4);
INSERT INTO Sentence (id,culture,value,length) VALUES (77,1036,'la dette',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (77,2058,'el empréstito',13);
INSERT INTO Sentence (id,culture,value,length) VALUES (78,1033,'Equipment',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (78,1036,'Équipement',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (78,2058,'Equipo',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (79,1033,'Payable',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (79,1036,'Payable',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (79,2058,'Pagadero',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (81,1033,'Salary',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (81,1036,'le salaire',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (81,2058,'Salario',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (82,1033,'Doubtful Accounts',17);
INSERT INTO Sentence (id,culture,value,length) VALUES (82,1036,'Compte douteux',14);
INSERT INTO Sentence (id,culture,value,length) VALUES (82,2058,'Cuentas dudosas',15);
INSERT INTO Sentence (id,culture,value,length) VALUES (83,1033,'Depreciation',12);
INSERT INTO Sentence (id,culture,value,length) VALUES (83,1036,'Dépréciation',12);
INSERT INTO Sentence (id,culture,value,length) VALUES (83,2058,'Depreciación',12);
INSERT INTO Sentence (id,culture,value,length) VALUES (84,1033,'General',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (84,1036,'Général',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (84,2058,'General',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (90,1033,'Receivable',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (90,1036,'Recevable',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (90,2058,'Cuenta por cobrar',17);
INSERT INTO Sentence (id,culture,value,length) VALUES (91,1033,'Current Assets',14);
INSERT INTO Sentence (id,culture,value,length) VALUES (91,1036,'Actifs actuels',14);
INSERT INTO Sentence (id,culture,value,length) VALUES (91,2058,'el activo disponible',20);
INSERT INTO Sentence (id,culture,value,length) VALUES (92,1033,'Retained Earnings',17);
INSERT INTO Sentence (id,culture,value,length) VALUES (92,1036,'Des bénéfices non répartis',26);
INSERT INTO Sentence (id,culture,value,length) VALUES (92,2058,'Ganancias retenidas',19);
INSERT INTO Sentence (id,culture,value,length) VALUES (93,1033,'Discounts',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (93,1036,'l' escompte',11);
INSERT INTO Sentence (id,culture,value,length) VALUES (93,2058,'Descuento',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (94,1033,'Service Charges',15);
INSERT INTO Sentence (id,culture,value,length) VALUES (94,1036,'les prix de services',20);
INSERT INTO Sentence (id,culture,value,length) VALUES (94,2058,'Cargos por servicio',19);
INSERT INTO Sentence (id,culture,value,length) VALUES (95,1033,'Charity',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (95,1036,'Charité',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (95,2058,'Caridad',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (96,1033,'Dining',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (96,1036,'À manger',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (96,2058,'Comida',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (97,1033,'Dues and Subscriptions',22);
INSERT INTO Sentence (id,culture,value,length) VALUES (97,1036,'Cotisation et abonnements',25);
INSERT INTO Sentence (id,culture,value,length) VALUES (97,2058,'cuotas y suscripciones',22);
INSERT INTO Sentence (id,culture,value,length) VALUES (98,1033,'Insurance',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (98,1036,'l' assurance',12);
INSERT INTO Sentence (id,culture,value,length) VALUES (98,2058,'Seguro',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (99,1033,'Licenses and Permits',20);
INSERT INTO Sentence (id,culture,value,length) VALUES (99,1036,'Licences et permis',18);
INSERT INTO Sentence (id,culture,value,length) VALUES (99,2058,'Licencias y permisos',20);
INSERT INTO Sentence (id,culture,value,length) VALUES (100,1033,'Supply',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (100,1036,'La fourniture',13);
INSERT INTO Sentence (id,culture,value,length) VALUES (100,2058,'Suministro',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (101,1033,'Rental',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (101,1036,'De location',11);
INSERT INTO Sentence (id,culture,value,length) VALUES (101,2058,'Alquiler',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (102,1033,'Miscellaneous',13);
INSERT INTO Sentence (id,culture,value,length) VALUES (102,1036,'varié',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (102,2058,'misceláneo',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (103,1033,'Payroll',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (103,1036,'Paie',4);
INSERT INTO Sentence (id,culture,value,length) VALUES (103,2058,'Nómina de sueldos',17);
INSERT INTO Sentence (id,culture,value,length) VALUES (104,1033,'Postage',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (104,1036,'l' affranchissement',19);
INSERT INTO Sentence (id,culture,value,length) VALUES (104,2058,'el franqueo',11);
INSERT INTO Sentence (id,culture,value,length) VALUES (105,1033,'Media',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (105,1036,'Médias',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (105,2058,'Medios de comunicación',22);
INSERT INTO Sentence (id,culture,value,length) VALUES (106,1033,'Professional Fees',17);
INSERT INTO Sentence (id,culture,value,length) VALUES (106,1036,'Honoraires professionnels',25);
INSERT INTO Sentence (id,culture,value,length) VALUES (106,2058,'Honorarios profesionales',24);
INSERT INTO Sentence (id,culture,value,length) VALUES (107,1033,'Rent',4);
INSERT INTO Sentence (id,culture,value,length) VALUES (107,1036,'Louer',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (107,2058,'Alquiler',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (108,1033,'Repairs',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (108,1036,'Réparations',11);
INSERT INTO Sentence (id,culture,value,length) VALUES (108,2058,'Refacción',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (109,1033,'Taxes',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (109,1036,'Impôts',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (109,2058,'Impuestos',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (110,1033,'Travel and Entertainment',24);
INSERT INTO Sentence (id,culture,value,length) VALUES (110,1036,'Voyage et divertissement',24);
INSERT INTO Sentence (id,culture,value,length) VALUES (110,2058,'Viajes y entretenimiento',24);
INSERT INTO Sentence (id,culture,value,length) VALUES (111,1033,'Utilities',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (111,1036,'Utilitaires',11);
INSERT INTO Sentence (id,culture,value,length) VALUES (111,2058,'Utilidades',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (112,1033,'Sales',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (112,1036,'Ventes',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (112,2058,'Ventas',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (113,1033,'Interest Income',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (113,1036,'Le revenu d'intérêts',20);
INSERT INTO Sentence (id,culture,value,length) VALUES (113,2058,'Ingresos por intereses',22);
INSERT INTO Sentence (id,culture,value,length) VALUES (114,1033,'Reimbursed Expenses',19);
INSERT INTO Sentence (id,culture,value,length) VALUES (114,1036,'Dépenses remboursées',20);
INSERT INTO Sentence (id,culture,value,length) VALUES (114,2058,'Gastos reembolsados',19);
INSERT INTO Sentence (id,culture,value,length) VALUES (115,1033,'Credit Card',11);
INSERT INTO Sentence (id,culture,value,length) VALUES (115,1036,'Carte de crédit',15);
INSERT INTO Sentence (id,culture,value,length) VALUES (115,2058,'Tarjeta de crédito',18);
INSERT INTO Sentence (id,culture,value,length) VALUES (116,1033,'Sales Credit',12);
INSERT INTO Sentence (id,culture,value,length) VALUES (116,1036,'Crédit de vente',15);
INSERT INTO Sentence (id,culture,value,length) VALUES (116,2058,'Crédito de ventas',17);
INSERT INTO Sentence (id,culture,value,length) VALUES (117,1033,'Purchases',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (117,1036,'Achats',6);
INSERT INTO Sentence (id,culture,value,length) VALUES (117,2058,'Compras',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (118,1033,'Purchases Debit',15);
INSERT INTO Sentence (id,culture,value,length) VALUES (118,1036,'Débit des achats',16);
INSERT INTO Sentence (id,culture,value,length) VALUES (118,2058,'Débito de compras',17);
INSERT INTO Sentence (id,culture,value,length) VALUES (119,1033,'Receipts',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (119,1036,'Reçus',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (119,2058,'Ingresos',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (120,1033,'Payments',8);
INSERT INTO Sentence (id,culture,value,length) VALUES (120,1036,'Paiements',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (120,2058,'Pagos',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (121,1033,'Petty Cash',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (121,1036,'Petite caisse',13);
INSERT INTO Sentence (id,culture,value,length) VALUES (121,2058,'Dinero para gastos menores',26);
INSERT INTO Sentence (id,culture,value,length) VALUES (122,1033,'Liabilities',11);
INSERT INTO Sentence (id,culture,value,length) VALUES (122,1036,'Passifs',7);
INSERT INTO Sentence (id,culture,value,length) VALUES (122,2058,'las deudas',10);
INSERT INTO Sentence (id,culture,value,length) VALUES (123,1033,'Loans',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (123,1036,'Prêts',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (123,2058,'Préstamos',9);
INSERT INTO Sentence (id,culture,value,length) VALUES (124,1033,'Loan Payment',12);
INSERT INTO Sentence (id,culture,value,length) VALUES (124,1036,'Paiement du prêt',16);
INSERT INTO Sentence (id,culture,value,length) VALUES (124,2058,'Pago de préstamo',16);
INSERT INTO Sentence (id,culture,value,length) VALUES (125,1033,'Supply Return',13);
INSERT INTO Sentence (id,culture,value,length) VALUES (125,1036,'Retour d'approvisionnement',26);
INSERT INTO Sentence (id,culture,value,length) VALUES (125,2058,'Devolución de suministro',24);
INSERT INTO Sentence (id,culture,value,length) VALUES (126,1033,'Sale',4);
INSERT INTO Sentence (id,culture,value,length) VALUES (126,1036,'Vente',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (126,2058,'Venta',5);
INSERT INTO Sentence (id,culture,value,length) VALUES (127,1033,'Equipment Return',16);
INSERT INTO Sentence (id,culture,value,length) VALUES (127,1036,'Retour d'équipement',19);
INSERT INTO Sentence (id,culture,value,length) VALUES (127,2058,'Devolución de equipo',20);
INSERT INTO Sentence (id,culture,value,length) VALUES (128,1033,'Petty Cash Return',17);
INSERT INTO Sentence (id,culture,value,length) VALUES (128,1036,'Retour de la petite caisse',26);
INSERT INTO Sentence (id,culture,value,length) VALUES (128,2058,'Devolución de caja chica',24);
--
INSERT INTO Sentence (id,culture,value,length) VALUES (200,1033,'Commission Sales',16);
INSERT INTO Sentence (id,culture,value,length) VALUES (200,1036,'Ventes à commission',19);
INSERT INTO Sentence (id,culture,value,length) VALUES (200,2058,'Ventas por comisión',19);
INSERT INTO Sentence (id,culture,value,length) VALUES (201,1033,'Commissions Payable',16);
INSERT INTO Sentence (id,culture,value,length) VALUES (201,1036,'Commissions à payer',19);
INSERT INTO Sentence (id,culture,value,length) VALUES (201,2058,'Comisiones a pagar',18);
INSERT INTO Sentence (id,culture,value,length) VALUES (210,1033,'Sale Jane Doe',13);
INSERT INTO Sentence (id,culture,value,length) VALUES (210,1036,'Vente Jane Doe',14);
INSERT INTO Sentence (id,culture,value,length) VALUES (210,2058,'Venta Jane Doe',14);
INSERT INTO Sentence (id,culture,value,length) VALUES (211,1033,'Sale John Doe',13);
INSERT INTO Sentence (id,culture,value,length) VALUES (211,1036,'Vente John Doe',14);
INSERT INTO Sentence (id,culture,value,length) VALUES (211,2058,'Venta John Doe',14);
