-- NuoDB database schema version 0.0.9 to 0.0.A
-- Changing IndividualList to ListIndividual
CREATE TABLE ListIndividual (
  id INTEGER,
  unlist TIMESTAMP,
  individual BIGINT NOT NULL,
  type INTEGER,
  created TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE ListIndividualName (
  listIndividual INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name INTEGER NOT NULL,
  listSet INTEGER,
  sequence SMALLINT,
  optinStyle SMALLINT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (listIndividual)
);

ALTER SEQUENCE LISTINDIVIDUALNAME$IDENTITY_SEQUENCE START WITH 2000000;

CREATE UNIQUE INDEX listindividualname_name_listset ON ListIndividualName (name, listSet);

CREATE OR REPLACE VIEW List AS
SELECT ListIndividual.id,
 ListIndividual.individual,
 ListIndividualName.name AS listName,
 Name.value AS listNameValue,
 ListIndividualName.listSet,
 ListSet.value AS listSetValue,
 ListIndividualName.sequence,
 CASE WHEN SendField.value IS NULL THEN 'to' ELSE SendField.value END AS send,
 ListIndividual.created
FROM ListIndividual
JOIN ListIndividualName ON ListIndividualName.ListIndividual = ListIndividual.id
 AND ListIndividualName.optinStyle = 1
JOIN Word AS Name ON ListIndividualName.name = Name.id
 AND Name.culture = ClientCulture()
LEFT JOIN Word AS ListSet ON ListIndividualName.listSet = ListSet.id
 AND ListSet.culture = ClientCulture()
LEFT JOIN Word AS SendField ON SendField.id = ListIndividual.type
 AND SendField.culture IS NULL
LEFT JOIN ListIndividual AS disable ON disable.individual = ListIndividual.individual
 AND disable.id IS NULL
 AND disable.unlist IS NULL
WHERE disable.individual IS NULL
 AND ListIndividual.unlist IS NULL
;

INSERT INTO ListIndividual (id, unlist, individual, created)
SELECT id, unlist, individual, created FROM IndividualList;

INSERT INTO ListIndividualName (listIndividual, name, listSet, sequence, optinStyle, created)
SELECT individualList, name, listSet, sequence, optinStyle, created FROM IndividualListName;

DROP TABLE IndividualListName;
DROP TABLE IndividualList;
