#!/usr/bin/env bash
# Concatenate PostgreSQL/procedures.d/*.sql in sorted order -> PostgreSQL/procedures.sql
# Source of truth is procedures.d/; procedures.sql is the loadable assemble artifact.
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
DIR="$ROOT/PostgreSQL/procedures.d"
OUT="$ROOT/PostgreSQL/procedures.sql"
if [[ ! -d "$DIR" ]]; then
  echo "missing $DIR" >&2
  exit 1
fi
# shellcheck disable=SC2012
mapfile -t FILES < <(ls -1 "$DIR"/*.sql | sort)
if [[ ${#FILES[@]} -eq 0 ]]; then
  echo "no .sql files in $DIR" >&2
  exit 1
fi
{
  echo "-- Assembled from PostgreSQL/procedures.d/ by scripts/assemble-pg-procedures.sh"
  echo "-- Do not edit this file by hand for new work; edit procedures.d/*.sql then re-run assemble."
  echo "-- Load order is lexicographic by filename (00-, 10-, … 99-)."
  echo ""
  for f in "${FILES[@]}"; do
    # strip trailing whitespace on each line; no space-only lines
    sed -e 's/[[:space:]]*$//' "$f" | sed -e '/^[[:space:]]\+$/d'
    # ensure file separation
    echo ""
  done
} > "$OUT"
# normalize: collapse excessive blank lines at most 2 consecutive? keep simple single blanks
# final newline
echo "Assembled ${#FILES[@]} files -> $OUT ($(wc -l < "$OUT") lines)"
